from model_lib.layers.spectral_batchnorm import SpectralBatchNormalization, SoftSpectralBatchNormalization
from model_lib.layers.spectral_normalization import SpectralNormalization, SoftSpectralNormalization
from model_lib.layers.spectral_normalization_conv import SpectralNormalizationConv, SoftSpectralNormalizationConv

from model_lib.layers.wrap_common_layers_sn import wrap_batchnorm, wrap_conv2D, wrap_dense, spectralnorm_wrapper
